[dependency-groups]
dev = [
  "deptry"
]

[project]
authors = [
  {name = "bencretois", email = "benjamin.cretois@nina.no"}
]
# PEP 621 project metadata
# See https://www.python.org/dev/peps/pep-0621/
dependencies = [
  "django-environ",
  "kaleido>=1.2.0",
  "matplotlib>=3.10.7",
  "numpy",
  "ollama>=0.6.1",
  "openai>=2.8.0",
  "pandas>=2.3.3",
  "plotly>=6.5.0",
  "py-zerox>=0.0.7",
  "scikit-learn>=1.7.2",
  "sentence-transformers>=5.1.2",
]
description = ""
license = "GPL-3.0+"
name = "ai-social-science"
readme = "README.md"
requires-python = ">=3.12"
version = "0.1.0"

[project.scripts]
ai-social-science = "main:start"

[tool.ruff]
fix = true

[tool.ruff.lint]
ignore = ["COM812"]
select = ["E", "W", "I", "F", "UP", "S", "B", "A", "COM", "LOG", "PTH", "Q"]
